### DISCUSSION TITLE
How to cut captions while preserving their tags?

### DISCUSSION THREAD

**Discussion by Rillke** [opencast/opencast#6424] [Ask Questions, Get Answers]
Tags on captions can indicate the language to the player. However, using the `editor` WOH, there is configuration like this:

```yml
  - id: editor
    exception-handler-workflow: partial-error
    description: " └── Cut the recording according to the edit decision list"
    configurations:
      - source-flavors: '*/work,captions/*'
      - smil-flavors: smil/tmp
      - target-smil-flavor: smil/tmp
      - target-flavor-subtype: trimmed
      - interactive: false
```

When we have a media package element with flavor `captions/vtt+de` and tags `archive, engage-download, engage-streaming, generator-type:auto, generator:auto:whisper:large-v3-turbo, lang:de, lang:deu, large-v3-turbo, stt, subopencast-ts-api, whisper` it ends up as `captions/trimmed` with no tags after cutting.

How to cut captions while preserving their tags?
