### ISSUE TITLE
Paella 7 Dependabot batcher is not getting triggered automatically

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#4279]
**Describe the bug**
The new Dependabot batcher #4240, is not getting automatically triggered when a new Dependabot paella 7 bump PR is created.

**To Reproduce**
1. Wait for any Dependabot PRs that is aimed to Paella 7
2. There is no automatic trigger on the automation list

**More information**

When I was working into this, the action was successfully triggered when the push or pull request it was being targeted to the desired branch, but it was aiming all PRs, this is the code.  Could it be another way to aim to the exact path of a triggering?

```
# Controls when the workflow will run
on:
  push:
    branches: [ "r/12.x", "develop" ]
  pull_request:
    branches: [ "r/12.x", "develop" ]
```
