### ISSUE TITLE
WorkflowInstance Regression and changed behavior

### ISSUE THREAD

**Issue by geichelberger** [opencast/opencast#4293]
Moving the workflows to the database changed the behavior of the WorkflowInstance, which could have introduced bugs or unwanted behavior to all workflow operation handlers.

Before the change, the MediaPackage could be retrieved by reference from the WorkflowInstance. The current implementation creates a deep copy by creating the MediaPackage object from parsing the corresponding string.

E.g., The editor operation handler (VideoEditorWorkflowOperationHandler) uses the WorkflowInstance to pass the modified MediaPackage to the following function. 

For me, the editor operation fails if the smil file does not exist and skip-processing is true.

https://github.com/opencast/opencast/blob/f9df8cc6f529232a91d59c4d3fd1aefa32b60f32/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstanceImpl.java#L425

vs

https://github.com/opencast/opencast/blob/f6a27211517dd8fe6da8fa3b1499fc33d98374ee/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java#L356

**To Reproduce**
```yaml
  - id: editor
    description: "Editor"
    configurations:
      - source-flavors: "*/source"
      - smil-flavors: "smil/doesnotexistbefore"
      - skip-processing: true
```
